ror/AudioCloud/config/routes.rb
AudioCloud::Application.routes.draw do
  resources :media_streams

   root 'media_streams#index'

end

ror/AudioCloud/app/models/media_stream.rb
class MediaStream < ActiveRecord::Base

	validates :name, :permalink_url, :url, :media_type, presence: true
	validates :name, length: {
		minimum: 1,
		maximum: 142,
		too_short: "must have at least %{count} words",
		too_long: "must have at most %{count} words"
	}


end

ror/AudioCloud/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

ror/AudioCloud/app/controllers/media_streams_controller.rb
class MediaStreamsController < ApplicationController
  before_action :set_media_stream, only: [:show, :edit, :update, :destroy]

  # GET /media_streams
  # GET /media_streams.json
  def index
    @media_streams = MediaStream.all

  end

  # GET /media_streams/1
  # GET /media_streams/1.json
  def show
  end

  # GET /media_streams/new
  def new
    @media_stream = MediaStream.new
  end

  # GET /media_streams/1/edit
  def edit
  end

  # POST /media_streams
  # POST /media_streams.json
  def create
    @media_stream = MediaStream.new(media_stream_params)

    respond_to do |format|
      if @media_stream.save
        format.html { redirect_to @media_stream, notice: 'Media stream was successfully created.' }
        format.json { render action: 'show', status: :created, location: @media_stream }
      else
        format.html { render action: 'new' }
        format.json { render json: @media_stream.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /media_streams/1
  # PATCH/PUT /media_streams/1.json
  def update
    respond_to do |format|
      if @media_stream.update(media_stream_params)
        format.html { redirect_to @media_stream, notice: 'Media stream was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @media_stream.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /media_streams/1
  # DELETE /media_streams/1.json
  def destroy
    @media_stream.destroy
    respond_to do |format|
      format.html { redirect_to media_streams_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_media_stream
      @media_stream = MediaStream.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def media_stream_params
      params.require(:media_stream).permit(:name, :detail, :permalink_url, :url, :download_url, :image_url, :media_type, :duration, :likes)
    end
end

ror/AudioCloud/app/helpers/application_helper.rb
module ApplicationHelper
end

ror/AudioCloud/app/helpers/media_streams_helper.rb
module MediaStreamsHelper
end

ror/AudioCloud/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AudioCloud</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

ror/AudioCloud/app/views/media_streams/_form.html.erb
<%= form_for(@media_stream) do |f| %>
  <% if @media_stream.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@media_stream.errors.count, "error") %> prohibited this media_stream from being saved:</h2>

      <ul>
      <% @media_stream.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :detail %><br>
    <%= f.text_field :detail %>
  </div>
  <div class="field">
    <%= f.label :permalink_url %><br>
    <%= f.text_field :permalink_url %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :download_url %><br>
    <%= f.text_field :download_url %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :media_type %><br>
    <%= f.number_field :media_type %>
  </div>
  <div class="field">
    <%= f.label :duration %><br>
    <%= f.number_field :duration %>
  </div>
  <div class="field">
    <%= f.label :likes %><br>
    <%= f.number_field :likes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ror/AudioCloud/app/views/media_streams/_media_stream.html.erb
<div data-track-container>

    <div class="span3">
        <%= media_stream.name %>
    </div>

    <div class="span3">
        <img src="<%= media_stream.image_url %>" />
    </div>

    <a data-audio-track data-behavior="play_audio_track" data-id="<%= media_stream.id %>" data-title="<%= media_stream.name %>" data-url="<%= media_stream.url %>" href="#">
        <i class="icon-play"></i>
    </a>

    <div class="span3">
        <%= media_stream.detail %>
    </div>

    <div class="span3">
        <%= link_to 'Show', media_stream %>
        <%= link_to 'Edit', edit_media_stream_path(media_stream) %>
        <%= link_to 'Destroy', media_stream, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
</div>

<hr>

ror/AudioCloud/app/views/media_streams/_media_streams_list.html.erb
<div data-music-container id="media_streams_list">

	<a data-behavior="player_switch_to_prev_track" href="#">PREV</a>
	|
	<a data-behavior="play_first_or_existing_track_on_page" href="#">PLAY</a>
	|
	<a data-behavior="player_switch_to_next_track" href="#">NEXT</a>




	<hr>

	<div data-music-container>
		<div data-track-container>
			<% @media_streams.each do |media_stream| %>
			<%= render "media_streams/media_stream", media_stream: media_stream %>
			<% end %>
		</div>
	</div>

</div>

ror/AudioCloud/app/views/media_streams/edit.html.erb
<h1>Editing media_stream</h1>

<%= render 'form' %>

<%= link_to 'Show', @media_stream %> |
<%= link_to 'Back', media_streams_path %>

ror/AudioCloud/app/views/media_streams/index.html.erb
<div class="container">
  <table>
    <tr>
      <div class="demo-headline">
        <h1 class="demo-logo">
          Audio cloud
          <small>Play all</small>
        </h1>
      </div>
    </tr>
  </table>

  <br>

  <%= render 'media_streams/media_streams_list' %>

  <br>


  <div class="row demo-row">
    <div class="col-md-3">
      <%= link_to 'New Media stream', new_media_stream_path, :class => 'btn btn-large btn-block btn-success' %>

    </div>

  </div>

ror/AudioCloud/app/views/media_streams/new.html.erb
<div class="container">
  <table>
    <tr>
        <div class="demo-headline">
          <h1 class="demo-logo logo">
            Audio cloud
            <small>Play all</small>
          </h1>
        </div>
    </tr>
  </table>

  <br>

<h1>New media_stream</h1>

<%= render 'form' %>

<%= link_to 'Back', media_streams_path %>

</div>

ror/AudioCloud/app/views/media_streams/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @media_stream.name %>
</p>

<p>
  <strong>Detail:</strong>
  <%= @media_stream.detail %>
</p>

<p>
  <strong>Permalink url:</strong>
  <%= @media_stream.permalink_url %>
</p>

<p>
  <strong>Url:</strong>
  <%= @media_stream.url %>
</p>

<p>
  <strong>Download url:</strong>
  <%= @media_stream.download_url %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @media_stream.image_url %>
</p>

<p>
  <strong>Media type:</strong>
  <%= @media_stream.media_type %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @media_stream.duration %>
</p>

<p>
  <strong>Likes:</strong>
  <%= @media_stream.likes %>
</p>

<%= link_to 'Edit', edit_media_stream_path(@media_stream) %> |
<%= link_to 'Back', media_streams_path %>

ror/AudioCloud/app/views/players/_audio_player.html.erb
<div>

    <ul data-music-container>
        <li data-track-container>
            <a data-audio-track data-behavior="play_audio_track" data-id="<%= media_stream.id %>" data-title="<%= media_stream.name %>" data-url="<%= media_stream.url %>" href="#">
                <i class="icon-play"></i>
            </a>
        </li>

    </ul>
</div>